#define TABLET_ID 1
#define MCU_ID 2
#define PERIPH_ID 3
#define BMS_ID 4
#define MC_ID 5

#define LEFT_PROJECTOR_LAMP 3
#define RIGHT_PROJECTOR_LAMP 5
#define LEFT_TURN_SIGNAL_FRONT 6
#define RIGHT_TURN_SIGNAL_FRONT 9
#define LEFT_TURN_SIGNAL_BACK 10
#define RIGHT_TURN_SIGNAL_BACK 11

#define SENSOR_1 A0
#define SENSOR_1_THRESH 10